# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aelhossini/Laila/OpenGL/Virtek_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aelhossini/Laila/OpenGL/Virtek_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aelhossini/Laila/OpenGL/Virtek_Project/CMakeFiles /home/aelhossini/Laila/OpenGL/Virtek_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aelhossini/Laila/OpenGL/Virtek_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named image

# Build rule for target.
image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 image
.PHONY : image

# fast build rule for target.
image/fast:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/build
.PHONY : image/fast

Image_Generator.o: Image_Generator.cpp.o

.PHONY : Image_Generator.o

# target to build an object file
Image_Generator.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Image_Generator.cpp.o
.PHONY : Image_Generator.cpp.o

Image_Generator.i: Image_Generator.cpp.i

.PHONY : Image_Generator.i

# target to preprocess a source file
Image_Generator.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Image_Generator.cpp.i
.PHONY : Image_Generator.cpp.i

Image_Generator.s: Image_Generator.cpp.s

.PHONY : Image_Generator.s

# target to generate assembly for a file
Image_Generator.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Image_Generator.cpp.s
.PHONY : Image_Generator.cpp.s

Object_Rend.o: Object_Rend.cpp.o

.PHONY : Object_Rend.o

# target to build an object file
Object_Rend.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Object_Rend.cpp.o
.PHONY : Object_Rend.cpp.o

Object_Rend.i: Object_Rend.cpp.i

.PHONY : Object_Rend.i

# target to preprocess a source file
Object_Rend.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Object_Rend.cpp.i
.PHONY : Object_Rend.cpp.i

Object_Rend.s: Object_Rend.cpp.s

.PHONY : Object_Rend.s

# target to generate assembly for a file
Object_Rend.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Object_Rend.cpp.s
.PHONY : Object_Rend.cpp.s

Resource_Manager.o: Resource_Manager.cpp.o

.PHONY : Resource_Manager.o

# target to build an object file
Resource_Manager.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Resource_Manager.cpp.o
.PHONY : Resource_Manager.cpp.o

Resource_Manager.i: Resource_Manager.cpp.i

.PHONY : Resource_Manager.i

# target to preprocess a source file
Resource_Manager.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Resource_Manager.cpp.i
.PHONY : Resource_Manager.cpp.i

Resource_Manager.s: Resource_Manager.cpp.s

.PHONY : Resource_Manager.s

# target to generate assembly for a file
Resource_Manager.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Resource_Manager.cpp.s
.PHONY : Resource_Manager.cpp.s

Scene.o: Scene.cpp.o

.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i

.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s

.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

Shader.o: Shader.cpp.o

.PHONY : Shader.o

# target to build an object file
Shader.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Shader.cpp.o
.PHONY : Shader.cpp.o

Shader.i: Shader.cpp.i

.PHONY : Shader.i

# target to preprocess a source file
Shader.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Shader.cpp.i
.PHONY : Shader.cpp.i

Shader.s: Shader.cpp.s

.PHONY : Shader.s

# target to generate assembly for a file
Shader.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Shader.cpp.s
.PHONY : Shader.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

home/aelhossini/Laila/OpenGL/glad/src/glad.o: home/aelhossini/Laila/OpenGL/glad/src/glad.c.o

.PHONY : home/aelhossini/Laila/OpenGL/glad/src/glad.o

# target to build an object file
home/aelhossini/Laila/OpenGL/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/home/aelhossini/Laila/OpenGL/glad/src/glad.c.o
.PHONY : home/aelhossini/Laila/OpenGL/glad/src/glad.c.o

home/aelhossini/Laila/OpenGL/glad/src/glad.i: home/aelhossini/Laila/OpenGL/glad/src/glad.c.i

.PHONY : home/aelhossini/Laila/OpenGL/glad/src/glad.i

# target to preprocess a source file
home/aelhossini/Laila/OpenGL/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/home/aelhossini/Laila/OpenGL/glad/src/glad.c.i
.PHONY : home/aelhossini/Laila/OpenGL/glad/src/glad.c.i

home/aelhossini/Laila/OpenGL/glad/src/glad.s: home/aelhossini/Laila/OpenGL/glad/src/glad.c.s

.PHONY : home/aelhossini/Laila/OpenGL/glad/src/glad.s

# target to generate assembly for a file
home/aelhossini/Laila/OpenGL/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/home/aelhossini/Laila/OpenGL/glad/src/glad.c.s
.PHONY : home/aelhossini/Laila/OpenGL/glad/src/glad.c.s

stb_image.o: stb_image.cpp.o

.PHONY : stb_image.o

# target to build an object file
stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/stb_image.cpp.o
.PHONY : stb_image.cpp.o

stb_image.i: stb_image.cpp.i

.PHONY : stb_image.i

# target to preprocess a source file
stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/stb_image.cpp.i
.PHONY : stb_image.cpp.i

stb_image.s: stb_image.cpp.s

.PHONY : stb_image.s

# target to generate assembly for a file
stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/stb_image.cpp.s
.PHONY : stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... image"
	@echo "... edit_cache"
	@echo "... Image_Generator.o"
	@echo "... Image_Generator.i"
	@echo "... Image_Generator.s"
	@echo "... Object_Rend.o"
	@echo "... Object_Rend.i"
	@echo "... Object_Rend.s"
	@echo "... Resource_Manager.o"
	@echo "... Resource_Manager.i"
	@echo "... Resource_Manager.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... Shader.o"
	@echo "... Shader.i"
	@echo "... Shader.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... home/aelhossini/Laila/OpenGL/glad/src/glad.o"
	@echo "... home/aelhossini/Laila/OpenGL/glad/src/glad.i"
	@echo "... home/aelhossini/Laila/OpenGL/glad/src/glad.s"
	@echo "... stb_image.o"
	@echo "... stb_image.i"
	@echo "... stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

